REGION_LIST = {
	'belgorodskaya_oblast': 'Белгородская область', 
	'bryanskaya_oblast': 'Брянская область', 
	'vladimirskaya_oblast': 'Владимирская область',
	'voronezhskaya_oblast': 'Воронежская область', 
	'ivanovskaya_oblast': 'Ивановская область',
	'kaluzhskaya_oblast': 'Калужская область',
	'kostromskaya_oblast': 'Костромская область',
	'kurskaya_oblast': 'Курская область',
	'lipetskaya_oblast': 'Липецкая область',
	'moskovskaya_oblast': 'Московская область',
	'orlovskaya_oblast': 'Орловская область',
	'ryazanskaya_oblast': 'Рязанская область',
	'smolenskaya_oblast': 'Смоленская область',
	'tambovskaya_oblast': 'Тамбовская область',
	'tverskaya_oblast': 'Тверская область',
	'tulskaya_oblast': 'Тульская область',
	'yaroslavskaya_oblast': 'Ярославская область',
	'moskva': 'Москва',
	'kareliya': 'Республика Карелия',
	'komi': 'Республика Коми',
	'arhangelskaya_oblast': 'Архангельская область',
	'nenetskiy_ao': 'Ненецкий-автономный округ',
	'vologodskaya_oblast': 'Вологодская область',
	'kaliningradskaya_oblast': 'Калининградская область',
	'leningradskaya_oblast': 'Ленинградская область',
	'murmanskaya_oblast': 'Мурманская область',
	'novgorodskaya_oblast': 'Новгородская область',
	'pskovskaya_oblast': 'Псковская область',
	'sankt-peterburg': 'Санкт-Петербург',
	'adygeya': 'Республика Адыгея',
	'dagestan': 'Республика Дагестан',
	'ingushetiya': 'Республика Ингушетия',
	'kabardino-balkariya': 'Республика Кабардино-Балкария',
	'kalmykiya': 'Республика Калмыкия',
	'karachaevo-cherkesiya': 'Карачаево-Черкесская Республика',
	'severnaya_osetiya': 'Республика Северная Осетия-Алания',
	'chechenskaya_respublika': 'Чеченская Республика',
	'krasnodarskiy_kray': 'Краснодарский край',
	'stavropolskiy_kray': 'Ставропольский край',
	'astrahanskaya_oblast': 'Астраханская область',
	'volgogradskaya_oblast': 'Вологодская область',
	'rostovskaya_oblast': 'Ростовская область',
	'bashkortostan': 'Республика Башкортостан',
	'mariy_el': 'Республика Марий Эл',
	'mordoviya': 'Республика Мордовия',
	'tatarstan': 'Республика Татарстан',
	'udmurtiya': 'Удмуртская Республика',
	'chuvashiya': 'Республика Чувашия',
	'kirovskaya_oblast': 'Кировская область',
	'nizhegorodskaya_oblast': 'Нижегородская область',
	'orenburgskaya_oblast': 'Оренбурская область',
	'penzenskaya_oblast': 'Пензенская область',
	'permskiy_kray': 'Пермский край',
	'samarskaya_oblast': 'Самарская область',
	'saratovskaya_oblast': 'Саратовская область',
	'ulyanovskaya_oblast': 'Ульяновская область',
	'kurganskaya_oblast': 'Курганская область',
	'sverdlovskaya_oblast': 'Свердловская область',
	'tyumenskaya_oblast': 'Тюменская область',
	'hanty-mansiyskiy_ao': 'Ханты-Мансийский автономный округ - Югра',
	'yamalo-nenetskiy_ao': 'Ямало-Ненецкий автономный округ',
	'chelyabinskaya_oblast': 'Челябинская область',
	'respublika_altay': 'Республика Алтай',
	'buryatiya': 'Республика Бурятия',
	'tyva': 'Республика Тыва',
	'hakasiya': 'Республика Хакасия',
	'altayskiy_kray': 'Алтайский край',
	'krasnoyarskiy_kray': 'Красноярский край',
	'irkutskaya_oblast': 'Иркутская область',
	'kemerovskaya_oblast': 'Кемеровская область',
	'novosibirskaya_oblast': 'Новосибирская область',
	'omskaya_oblast': 'Омская область',
	'tomskaya_oblast': 'Томская область',
	'zabaykalskiy_kray': 'Забайкальский край',
	'saha_yakutiya': 'Республика Саха (Якутия)',
	'primorskiy_kray': 'Приморский край',
	'habarovskiy_kray': 'Хабаровский край',
	'amurskaya_oblast': 'Амурская область',
	'kamchatskiy_kray': 'Камчатский край',
	'magadanskaya_oblast': 'Магаданская область',
	'sahalinskaya_oblast': 'Сахалинская область',
	'evreyskaya_ao': 'Еврейская автономная область',
	'chukotskiy_ao': 'Чукотский автономный округ'
	}